config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
resources :projects do
  resources :materials
end

resources :projects do
  resources :materials do
    resources :material_cycles do
      collection do
        get "entry"
        get "middle"
        get "exit"
      end
    end
  end
  resources :material_imports, :only => [:new, :create, :show] do
    member do
      get :settings
      post :settings
      get :mapping
      post :mapping
      get :run
      post :run
    end
  end
end

resources :material_categories

resources :warehouses

resources :materials, :only => [:index, :show]

resources :material_comments, :only => [:create, :destroy]

match 'auto_completes/materials' => 'auto_completes#materials', :via => :get, :as => 'auto_complete_materials'

app/views/importers/mapping/_material.html.erb
<%= form_tag(mapping_project_material_import_path(:id => @import, :project => @project), :id => "import-form") do %>
  <fieldset class="box tabular">
    <legend><%= l(:label_fields_mapping) %></legend>
    <div id="fields-mapping">
      <%= render :partial => 'importers/mapping/material_fields_mapping' %>
    </div>
  </fieldset>

<%= render :partial => 'importers/preview' %>
<% end %>

app/views/importers/mapping/_material_fields_mapping.html.erb
<div class="splitcontent">
  <div class="splitcontentleft">
    <p>
      <label><%= l(:field_inner_code) %></label>
      <%= mapping_select_tag @import, 'inner_code', :required => true %>
    </p>
    <p>
      <label><%= l(:field_material_name) %></label>
      <%= mapping_select_tag @import, 'name', :required => true %>
    </p>
    <p>
      <label><%= l(:field_brand) %></label>
      <%= mapping_select_tag @import, 'brand' %>
    </p>
    <p>
      <label><%= l(:field_amount) %></label>
      <%= mapping_select_tag @import, 'amount' %>
    </p>
    <p>
      <label><%= l(:field_original_value) %></label>
      <%= mapping_select_tag @import, 'original_value' %>
    </p>
    <p>
      <label><%= l(:field_current_value) %></label>
      <%= mapping_select_tag @import, 'current_value' %>
    </p>
    <p>
      <label><%= l(:field_purchaser) %></label>
      <%= mapping_select_tag @import, 'purchaser' %>
    </p>
    <p>
      <label><%= l(:field_purchase_at) %></label>
      <%= mapping_select_tag @import, 'purchase_at' %>
    </p>
    <p>
      <label><%= l(:field_user) %></label>
      <%= mapping_select_tag @import, 'user' %>
    </p>
    <p>
      <label><%= l(:field_use_since) %></label>
      <%= mapping_select_tag @import, 'use_since' %>
    </p>
    <p>
      <label><%= l(:field_handover) %></label>
      <%= mapping_select_tag @import, 'handover' %>
    </p>
    <p>
      <label><%= l(:field_handover_at) %></label>
      <%= mapping_select_tag @import, 'handover_since' %>
    </p>
  </div>

  <div class="splitcontentright">
    <p>
      <label><%= l(:field_location) %></label>
      <%= mapping_select_tag @import, 'location' %>
    </p>
    <p>
      <label><%= l(:field_location_since) %></label>
      <%= mapping_select_tag @import, 'location_since' %>
    </p>
    <p>
      <label><%= l(:field_responsible_by) %></label>
      <%= mapping_select_tag @import, 'responsible_by' %>
    </p>
    <p>
      <label><%= l(:field_owner) %></label>
      <%= mapping_select_tag @import, 'owner' %>
    </p>
    <p>
      <label><%= l(:field_status) %></label>
      <%= mapping_select_tag @import, 'status' %>
    </p>
    <p>
      <label><%= l(:field_property) %></label>
      <%= mapping_select_tag @import, 'property' %>
    </p>
    <p>
      <label><%= l(:field_remark) %></label>
      <%= mapping_select_tag @import, 'remark' %>
    </p>
    <p>
      <label><%= l(:field_detail) %></label>
      <%= mapping_select_tag @import, 'detail' %>
    </p>
  </div>
</div>