config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
resources :projects do
  resources :materials
end

resources :projects do
  resources :materials do
    resources :material_cycles do
      collection do
        get "entry"
        get "middle"
        get "exit"
      end
    end
  end
  resources :material_imports, :only => [:new, :create, :show] do
    member do
      get :settings
      post :settings
      get :mapping
      post :mapping
      get :run
      post :run
    end
  end
end

resources :material_categories

resources :warehouses

resources :materials, :only => [:index, :show]

resources :material_comments, :only => [:create, :destroy]

match 'auto_completes/materials' => 'auto_completes#materials', :via => :get, :as => 'auto_complete_materials'

app/views/settings/_material_categories.html.erb
<div class="contextual">
<%= link_to l(:label_material_category_new), {:controller => "material_categories", :action => 'new'}, :class => 'icon icon-add' %>
</div>

<h3><%=l(:label_material_categories)%></h3>
 
<table class="list">
  <thead><tr>
  <th><%=l(:field_material_category)%></th>
  <th><%=l(:field_material_category_code)%></th>
  <th></th>
  </tr></thead>
  <tbody>
    <% MaterialCategory.category_tree(MaterialCategory.order('lft')) do |category, level| %>
      <tr class="<%= cycle("odd", "even") %> project <%= category.css_classes %> <%= level > 0 ? "idnt idnt-#{level}" : nil %>">
      <td class="name"><span><%= link_to category.name, edit_material_category_path(category) %></span></td>
      <td class="code"><span><%= category.code %></span></td>
      <td class="buttons">
        <%= delete_link material_category_path(category) %>
      </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/settings/_material_general.html.erb
<p>
  <label><%= l(:label_material_show_in_top_menu) %></label>
  <%= hidden_field_tag 'settings[show_in_top_menu]', 0, :id => nil %>
  <%= check_box_tag 'settings[show_in_top_menu]', 1, @settings["show_in_top_menu"].to_i > 0 %>
</p>

app/views/settings/_materials.html.erb
<% materials_tabs = [{:name => 'general', :partial => 'settings/material_general', :label => :label_general},
        {:name => 'material_categories', :partial => 'settings/material_categories', :label => :label_material_categories},
        {:name => 'warehouses', :partial => 'settings/warehouses', :label => :label_warehouses}
        ]   %>   

<%= render_tabs materials_tabs %>

<% html_title(l(:label_settings), l(:label_materials)) -%>  

app/views/settings/_warehouses.html.erb
<div class="contextual">
<%= link_to l(:label_warehouse_new), {:controller => "warehouses", :action => 'new'}, :class => 'icon icon-add' %>
</div>

<h3><%=l(:label_warehouses)%></h3>
 
<table class="list">
  <thead><tr>
  <th><%=l(:field_warehouse_code)%></th>
  <th><%=l(:field_warehouse_name)%></th>
  <th><%=l(:field_warehouse_type)%></th>
  <th><%=l(:field_responsible_by)%></th>
  <th></th>
  </tr></thead>
  <tbody>
    <% @warehouses = Warehouse.all %>
    <% if @warehouses.empty? %>
      <p class="nodata"><%= l(:label_no_data) %></p>
    <% else %>
      <% @warehouses.each do |warehouse| %>
        <tr class="<%= cycle 'odd', 'even' %>">
          <td class="code"><span><%= link_to warehouse.code, edit_warehouse_path(warehouse) %></span></td>
          <td class="name"><span><%= link_to warehouse.name, edit_warehouse_path(warehouse) %></span></td>
          <td class="type"><span><%= warehouse.type_name %></span></td>
          <td class="responsible_by"><span><%= warehouse.responsible_by ? warehouse.responsible_by.name : '-' %></span></td>
          <td class="buttons">
          <%= delete_link warehouse_path(warehouse) %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/settings/index.html.erb
<div class="contextual">

<%= link_to_if_authorized l(:label_material_new), {:controller => "materials", :action => "new", :project_id => @project}, :class => 'icon icon-add' %>

</div>

<% html_title(@query.new_record? ? l(:label_materials) : @query.name) %>
<h2><%= @query.new_record? ? l(:label_materials) : @query.name %></h2>

<%= form_tag({ :controller => 'materials', :action => 'index', :project_id => @project },
            :method => :get, :id => 'query_form') do %>
  <div id="query_form_with_buttons" class="hide-when-print">
    <%= hidden_field_tag 'set_filter', '1' %>
    <div id="query_form_content">
    <fieldset id="filters" class="collapsible <%= @query.new_record? ? "" : "collapsed" %>">
      <legend onclick="toggleFieldset(this);"><%= l(:label_filter_plural) %></legend>
      <div style="<%= @query.new_record? ? "" : "display: none;" %>">
        <%= render :partial => 'queries/filters', :locals => {:query => @query} %>
      </div>
    </fieldset>
    <fieldset class="collapsible collapsed">
      <legend onclick="toggleFieldset(this);"><%= l(:label_options) %></legend>
      <div style="display: none;">
        <table>
          <tr>
            <td><%= l(:field_column_names) %></td>
            <td><%= render_query_columns_selection(@query) %></td>
          </tr>
          <tr>
            <td><label for='group_by'><%= l(:field_group_by) %></label></td>
            <td><%= select_tag('group_by',
                               options_for_select(
                                 [[]] + @query.groupable_columns.collect {|c| [c.caption, c.name.to_s]},
                                 @query.group_by)
                       ) %></td>
          </tr>
          <tr>
            <td><%= l(:button_show) %></td>
            <td><%= available_block_columns_tags(@query) %></td>
          </tr>
          <tr>
            <td><%= l(:label_total_plural) %></td>
            <td><%= available_totalable_columns_tags(@query) %></td>
          </tr>
        </table>
      </div>
    </fieldset>
    </div>
    <p class="buttons">
    <%= link_to_function l(:button_apply), '$("#query_form").submit()', :class => 'icon icon-checked' %>
    <%= link_to l(:button_clear), { :set_filter => 1, :project_id => @project }, :class => 'icon icon-reload'  %>
    <% if @query.new_record? && User.current.allowed_to?(:save_queries, @project, :global => true) %>
        <%= link_to_function l(:button_save),
                             "$('#query_form').attr('action', '#{ @project ? new_project_query_path(@project) : new_query_path }').submit()",
                             :class => 'icon icon-save' %>
    <% end %>
    </p>
  </div>
<% end %>

<%= error_messages_for 'query' %>
<% if @query.valid? %>
  <% if @materials.empty? %>
    <p class="nodata"><%= l(:label_no_data) %></p>
  <% else %>
    <%= render_query_totals(@query) %>
    <%= render :partial => 'list', :locals => {:materials => @materials, :query => @query} %>
    <span class="pagination"><%= pagination_links_full @materials_pages, @materials_count %></span>
  <% end %>
  <% other_formats_links do |f| %>
      <%= f.link_to 'CSV', :url => params %>
  <% end %>
<% end %>