config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
resources :projects do
  resources :materials
end

resources :projects do
  resources :materials do
    resources :material_cycles do
      collection do
        get "entry"
        get "middle"
        get "exit"
      end
    end
  end
  resources :material_imports, :only => [:new, :create, :show] do
    member do
      get :settings
      post :settings
      get :mapping
      post :mapping
      get :run
      post :run
    end
  end
end

resources :material_categories

resources :warehouses

resources :materials, :only => [:index, :show]

resources :material_comments, :only => [:create, :destroy]

match 'auto_completes/materials' => 'auto_completes#materials', :via => :get, :as => 'auto_complete_materials'

app/controllers/material_cycles_controller.rb
class MaterialCyclesController < ApplicationController
  before_action :find_project_by_project_id, :only => [:new, :entry, :middle, :exit, :create, :show, :edit, :destroy, :update]
  before_action :find_material_by_material_id, :only => [:index, :new, :entry, :middle, :exit, :create, :show, :edit, :destroy, :update]
  before_action :set_material_cycle, only: [:show, :edit, :update, :destroy]
  before_action :find_optional_project, :only => :index

  helper :issues
  helper :sort
  include SortHelper
  helper :queries
  include QueriesHelper
  helper :material_queries
  include MaterialQueriesHelper
  
  def new
    @material_cycle = @material.material_cycles.new
    @material_cycle.project = @project
    
    (render_403; return false) unless @material_cycle.creatable_by?(User.current, @project)
    
    # set default
    @material_cycle.author = User.current
  end
  
  def entry
    (render_403; return false) unless @material.can_cycle_entry?

    @material_cycle = @material.material_cycles.build
    @material_cycle.project = @project
    (render_403; return false) unless @material_cycle.creatable_by?(User.current, @project)

    redirect_to new_project_issue_path(@project, :material_cycle_stage => MaterialCycle::STAGE_ENTRY, :material_id => @material.id)
  end

  def middle
    (render_403; return false) unless @material.can_cycle_middle?

    @material_cycle = @material.material_cycles.build
    @material_cycle.project = @project
    
    (render_403; return false) unless @material_cycle.creatable_by?(User.current, @project)
    
    redirect_to new_project_issue_path(@project, :material_cycle_stage => MaterialCycle::STAGE_MIDDLE, :material_id => @material.id)
  end
  
  def exit
    (render_403; return false) unless @material.can_cycle_exit?
    
    @material_cycle = @material.material_cycles.build
    @material_cycle.project = @project
    
    (render_403; return false) unless @material_cycle.creatable_by?(User.current, @project)
    
    redirect_to new_project_issue_path(@project, :material_cycle_stage => MaterialCycle::STAGE_EXIT, :material_id => @material.id)
  end

  def index
    @query = MaterialCycleQuery.build_from_params(params, :project => @project, :name => '_')
    # retrieve_query('material_cycle')
    sort_init(@query.sort_criteria.empty? ? [['updated_date', 'desc']] : @query.sort_criteria)
    sort_update(@query.sortable_columns)
    
    scope = material_cycle_scope(:order => sort_clause).
      includes(:project, :material, :issue)

    respond_to do |format|
      format.html {
        @material_cycles_count = scope.count
        @material_cycles_pages = Paginator.new @material_cycles_count, per_page_option, params['page']
        @material_cycles = scope.offset(@material_cycles_pages.offset).limit(@material_cycles_pages.per_page).to_a
        render :layout => !request.xhr?
      }
      # format.api
      # format.csv { send_data(material_cycles_to_csv(@material_cycles), :type => 'text/csv; header=present', :filename => 'material_cycles.csv') }
    end
  end


  def edit
    (render_403; return false) unless @material_cycle.editable_by?(User.current)
  end
  
  def show
    (render_403; return false) unless @material_cycle.visible?(User.current)
  end
  
  def destroy
    (render_403; return false) unless @material_cycle.destroyable_by?(User.current)
    
    if @material_cycle.destroy
      flash[:notice] = l(:notice_successful_delete)
    else
      flash[:error] = l(:notice_unsuccessful_save)
    end
    
    respond_to do |format|
      format.html { redirect_to :action => "index", :project_id => @material.project }
      format.api  { head :ok }
    end
  end
  
  def create
    @material_cycle = @material.material_cycles.build(material_cycle_params)
    (render_403; return false) unless @material_cycle.creatable_by?(User.current, @project)
    @material_cycle.author = User.current
    @material_cycle.project = @project
    stage = params[:stage]
    @material_cycle.stage = stage
    
    respond_to do |format|
      if @material_cycle.save
        flash[:notice] = l(:notice_material_cycle_create_success)
        format.html { redirect_to :action => "show", :id => @material_cycle}
        format.json { render :show, status: :created, location: @material_cycle }
      else
        format.html { render :new }
        format.json { render json: @material_cycle.errors, status: l(:notice_material_cycle_create_fail) }
      end
    end
  end
  
  def update
    (render_403; return false) unless @material_cycle.editable_by?(User.current)
    if @material_cycle.update_attributes(material_cycle_params)
      flash[:notice] = l(:notice_material_cycle_update_success)
      respond_to do |format|
        format.html { redirect_to :action => "show", :id => @material_cycle }
        format.api  { head :ok }
      end
    else
      respond_to do |format|
        format.html { render :action => "edit"}
        format.api  { render_validation_errors(@material_cycle) }
      end
    end
  end
  
  
  private 
      def material_cycle_scope(options={})
        scope = @query.results_scope(options)
        if @material
          scope = scope.on_material(@material)
        end
        scope
      end
      
      def material_cycle_params
      params.require(:material_cycle).permit( :project_id,
                                      :material_id,
                                      :issue_id,
                                      :brand,
                                      :stage,
                                      :event_type,
                                      :order_no,
                                      :direction,
                                      :value,
                                      :location,
                                      :warehouse,
                                      :warehouse_id,
                                      :outsider,
                                      :purpose)
    end

    def find_material_by_material_id
        # Find material of id params[:project_id]
      @material = Material.find(params[:material_id])
      rescue ActiveRecord::RecordNotFound
      render_404
    end
    
    def set_material_cycle
      @material_cycle = MaterialCycle.find(params[:id])
    end
end

app/helpers/material_cycles_helper.rb
module MaterialCyclesHelper
  # define the status' enum list
  def collection_for_stage_select
    [[l(:label_material_cycle_stage_entry), MaterialCycle::STAGE_ENTRY],
     [l(:label_material_cycle_stage_middle), MaterialCycle::STAGE_MIDDLE],
     [l(:label_material_cycle_stage_exit), MaterialCycle::STAGE_EXIT]]
  end
  
  # define the type's enum list
  def collection_for_type_select(stage=nil)
    case stage
    when nil
      [[l(:label_material_cycle_event_type_buy_in), MaterialCycle::TYPE_BUY_IN],
       [l(:label_material_cycle_event_type_sell_out), MaterialCycle::TYPE_SELL_OUT],
       [l(:label_material_cycle_event_type_rent), MaterialCycle::TYPE_RENT],
       [l(:label_material_cycle_event_type_rent_out), MaterialCycle::TYPE_RENT_OUT],
       [l(:label_material_cycle_event_type_borrow), MaterialCycle::TYPE_BORROW],
       [l(:label_material_cycle_event_type_loan), MaterialCycle::TYPE_LOAN],
       [l(:label_material_cycle_event_type_stock_in), MaterialCycle::TYPE_STOCK_IN],
       [l(:label_material_cycle_event_type_stock_out), MaterialCycle::TYPE_STOCK_OUT],
       [l(:label_material_cycle_event_type_get), MaterialCycle::TYPE_GET],
       [l(:label_material_cycle_event_type_give), MaterialCycle::TYPE_GIVE],
       [l(:label_material_cycle_event_type_scrap), MaterialCycle::TYPE_SCRAP],
       [l(:label_material_cycle_event_type_return), MaterialCycle::TYPE_RETURN],
       [l(:label_material_cycle_event_type_discard), MaterialCycle::TYPE_DISCARD],
       [l(:label_material_cycle_event_type_loss), MaterialCycle::TYPE_LOSS],
       [l(:label_material_cycle_event_type_lock), MaterialCycle::TYPE_LOCK],
       [l(:label_material_cycle_event_type_unknown), MaterialCycle::TYPE_UNKNOWN]]

    when MaterialCycle::STAGE_ENTRY
      [[l(:label_material_cycle_event_type_buy_in), MaterialCycle::TYPE_BUY_IN],
       [l(:label_material_cycle_event_type_rent), MaterialCycle::TYPE_RENT],
       [l(:label_material_cycle_event_type_borrow), MaterialCycle::TYPE_BORROW],
       [l(:label_material_cycle_event_type_get), MaterialCycle::TYPE_GET]]
    when MaterialCycle::STAGE_MIDDLE
      [[l(:label_material_cycle_event_type_rent), MaterialCycle::TYPE_RENT],
       [l(:label_material_cycle_event_type_rent_out), MaterialCycle::TYPE_RENT_OUT],
       [l(:label_material_cycle_event_type_borrow), MaterialCycle::TYPE_BORROW],
       [l(:label_material_cycle_event_type_loan), MaterialCycle::TYPE_LOAN],
       [l(:label_material_cycle_event_type_stock_in), MaterialCycle::TYPE_STOCK_IN],
       [l(:label_material_cycle_event_type_stock_out), MaterialCycle::TYPE_STOCK_OUT],
       [l(:label_material_cycle_event_type_get), MaterialCycle::TYPE_GET],
       [l(:label_material_cycle_event_type_give), MaterialCycle::TYPE_GIVE]]
    when MaterialCycle::STAGE_EXIT
      [[l(:label_material_cycle_event_type_scrap), MaterialCycle::TYPE_SCRAP],
       [l(:label_material_cycle_event_type_return), MaterialCycle::TYPE_RETURN],
       [l(:label_material_cycle_event_type_discard), MaterialCycle::TYPE_DISCARD],
       [l(:label_material_cycle_event_type_loss), MaterialCycle::TYPE_LOSS],
       [l(:label_material_cycle_event_type_lock), MaterialCycle::TYPE_LOCK]]
   end
  end
 
  # define the direction's enum list
  def collection_for_direction_select
    [[l(:label_material_cycle_direction_from), MaterialCycle::DIRECTION_FROM],
     [l(:label_material_cycle_direction_to), MaterialCycle::DIRECTION_TO]]
  end

  # define the purpose's enum list
  def collection_for_purpose_select
    [[l(:label_material_cycle_purpose_usage), MaterialCycle::PURPOSE_USAGE],
     [l(:label_material_cycle_purpose_store), MaterialCycle::PURPOSE_STORE],
     [l(:label_material_cycle_purpose_maintain), MaterialCycle::PURPOSE_MAINTAIN],
     [l(:label_material_cycle_purpose_repair), MaterialCycle::PURPOSE_REPAIR],
     [l(:label_material_cycle_purpose_unknown), MaterialCycle::PURPOSE_UNKNOWN]]
  end
  
  def warehouses_for_select
    Warehouse.all.map{|a| [a.name, a.id.to_s]}
  end
  
  def issue_subject_pre
        case stage
    when nil
      l(:label_material_cycle_nil_issue_subject)
    when MaterialCycle::STAGE_ENTRY
      l(:label_material_cycle_entry_issue_subject)
    when MaterialCycle::STAGE_MIDDLE
       l(:label_material_cycle_middle_issue_subject)
    when MaterialCycle::STAGE_EXIT
       l(:label_material_cycle_exit_issue_subject)
   end
  end
end

app/views/material_cycles/_form.html.erb
<%= error_messages_for 'material_cycle' %>

<div class="box tabular attributes">

<script type="text/javascript" charset="utf-8">
	function eventChange(element) {
    if (element.value == '<%= MaterialCycle::TYPE_STOCK_IN %>'
    || element.value == '<%= MaterialCycle::TYPE_STOCK_OUT %>' ) {
      $('#warehouse_id').children().prop('disabled',false);
		} else {
		  $('#warehouse_id').children().prop('disabled',true);
		}

	}
</script>



  <div class="splitcontentleft">
    <p class="object-select"><%= f.select :stage, collection_for_stage_select, {}, :disabled => true, :required => true %></p>
    <p class="object-select"><%= f.select :event_type, collection_for_type_select(@material_cycle.stage), {}, :onchange => "eventChange(this)", :required => true %></p>
    <p id="location"> <%= f.text_field :location, :label => :field_location %></p>
    <% if [MaterialCycle::TYPE_STOCK_IN,  MaterialCycle::TYPE_STOCK_OUT].include?(@material_cycle.event_type) %>
    <p id="warehouse_id" class="object-select"><%= f.select :warehouse_id, warehouses_for_select, {:include_blank => true} %></p>
    <% else %> 
    <p id="warehouse_id" class="object-select"><%= f.select :warehouse_id, warehouses_for_select, {:include_blank => true}, :disabled => true %></p>
    <% end %>
    <p>
      <%= f.text_field :issue_id, :size => 6 %>
      <% if @material_cycle.issue.try(:visible?) %>
      <span id="time_entry_issue"><%= "#{@material_cycle.issue.tracker.name} ##{@material_cycle.issue.id}: #{@material_cycle.issue.subject}" %></span>
    <% end %>
    </p>
  </div>

  <div class="splitcontentright">
    <p><%= f.text_field :order_no, :label => :field_order_no %></p>
    <p><%= f.text_field :value, :label => l(:field_value), :size => 10 %></p>
    <p><%= f.text_field :outsider, :label => :field_outsider %></p>
    <p class="object-select"><%= f.select :purpose, collection_for_purpose_select, :label => l(:field_purpose) %></p>
    <p></p>
    <p></p>
  </div>
</div>

<%= javascript_tag do %>
  observeAutocompleteField('material_cycle_issue_id', '<%= escape_javascript auto_complete_issues_path(:project_id => @project, :scope => (@project ? nil : 'all'))%>', {
    select: function(event, ui) {
      $('#material_cycle_issue').text(ui.item.label);
      $('#material_cycle_issue_id').blur();
    }
  });
<% end %>

app/views/material_cycles/_issue_cycle.html.erb
<% if @issue.new_record? && @issue.material_cycle && !@copy_from && User.current.allowed_to?(:new_material_cycles, @project) %>

<% @issue.build_material_cycle if @issue.material_cycle.blank? %>

<h2><%= l(:label_material_cycle_issue) %></h2>
<%= form.fields_for :material_cycle do |f| %>
<%= error_messages_for 'material_cycle' %>

<div class="box tabular attributes">

<script type="text/javascript" charset="utf-8">
	function eventChange(element) {
    if (element.value == '<%= MaterialCycle::TYPE_STOCK_IN %>'
    || element.value == '<%= MaterialCycle::TYPE_STOCK_OUT %>' ) {
      $('#warehouse_id').children().prop('disabled',false);
		} else {
		  $('#warehouse_id').children().prop('disabled',true);
		}

	}
</script>
  <div class="splitcontentleft">
    <p class="object-select"><%= f.select :stage, collection_for_stage_select, {}, :disabled => true %></p>
    <%= f.hidden_field :stage, :label => :field_stage, :value => @issue.material_cycle.stage %>
    <%= f.hidden_field :project_id, :label => :field_project, :value => @issue.material_cycle.project_id %>
    <p class="object-select"><%= f.select :event_type, collection_for_type_select(@issue.material_cycle.stage), {}, :onchange => "eventChange(this)" %></p>
    <p id="location"> <%= f.text_field :location, :label => :field_location, :value => @issue.material_cycle.location  %></p>
    <% if [MaterialCycle::TYPE_STOCK_IN,  MaterialCycle::TYPE_STOCK_OUT].include?(@issue.material_cycle.event_type) %>
    <p id="warehouse_id" class="object-select"><%= f.select :warehouse_id, warehouses_for_select, {:include_blank => true} %></p>
    <% else %> 
    <p id="warehouse_id" class="object-select"><%= f.select :warehouse_id, warehouses_for_select, {:include_blank => true}, :disabled => true %></p>
    <% end %>
  </div>

  <div class="splitcontentright">
    <p><%= f.text_field :order_no, :label => :field_order_no, :value => @issue.material_cycle.order_no %></p>
    <p><%= f.text_field :value, :label => l(:field_value), :size => 10, :value => @issue.material_cycle.value %></p>
    <p><%= f.text_field :outsider, :label => :field_outsider, :value => @issue.material_cycle.outsider %></p>
    <%= f.hidden_field :material_id, :label => :field_material, :value => @issue.material_cycle.material_id %>
    <%= f.hidden_field :author_id, :label => :field_author, :value => @issue.material_cycle.author_id %>
    <p class="object-select"><%= f.select :purpose, collection_for_purpose_select, :label => l(:field_purpose) %></p>
  </div>
</div>

<% end -%>
<% end -%>

app/views/material_cycles/_issue_cycle_show.html.erb
<% return if @issue.material_cycle.blank? %>
<% @material_cycle = @issue.material_cycle %>
<% @project = @material_cycle.project %>
<% return unless @project.module_enabled?(:redmine_materials) %> 
<% @material = @material_cycle.material %>
<h2>
  <%= link_to("#{l(:label_material_belong)} #{l(:label_material)} ##{@material.id}", project_material_path(@project, @material)) %>
</h2>

<div class="issue details">
  <div class="subject">
  <h3>
    <%= "#{l(:label_material_cycle)} ##{@material_cycle.id}" %>
  </h3>
  </div>
  <p class="author">
    <%= authoring @material_cycle.created_at, @material_cycle.author %>.
    <% if @material_cycle.created_at != @material_cycle.updated_at %>
      <%= l(:label_updated_time, time_tag(@material_cycle.updated_at)).html_safe %>.
    <% end %>
  </p>
  
  <<%= Redmine::VERSION.to_s > '3.2' ? 'div' : 'table' %> class="attributes">
    <%= issue_fields_rows do |rows|
      rows.left l(:field_stage), @material_cycle.stage_name
      rows.right l(:field_event_type), @material_cycle.type_name
      rows.left l(:field_order_no), @material_cycle.order_no
      rows.right l(:field_location), @material_cycle.location
      rows.left l(:field_outsider), @material_cycle.outsider
      rows.right l(:field_value), @material_cycle.value
      rows.left l(:field_location), @material_cycle.location
      rows.right l(:field_purpose), @material_cycle.purpose_name
      rows.left l(:field_warehouse), @material_cycle.warehouse.nil? ? "-" : @material_cycle.warehouse.name
    end %>
  </<%= Redmine::VERSION.to_s > '3.2' ? 'div' : 'table' %>>
  

app/views/material_cycles/_list.html.erb
<%= form_tag({}) do -%>
<%= hidden_field_tag 'back_url', url_for(params), :id => nil %>
<div class="autoscroll">
  <table class="list material_cycles issues">
    <thead>
      <tr>
        <th class="checkbox hide-when-print">
          <%= check_box_tag 'check_all', '', false, :class => 'toggle-selection',
                :title => "#{l(:button_check_all)}/#{l(:button_uncheck_all)}" %>
        </th>
        <th>#</th>
        <% @query.inline_columns.each do |column| %>
          <%= Redmine::VERSION.to_s >= '3.4' ? column_header(@query, column) : column_header(column) %>
        <% end %>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% material_cycles.each do |material_cycle| -%>
      <tr id="material_cycle-<%= material_cycle.id %>" class="material_cycle <%= cycle('odd', 'even') %>">
        <td class="checkbox hide-when-print"><%= check_box_tag("ids[]", material_cycle.id, false, :id => nil) %></td>
        <td class="id"><%= link_to material_cycle.id, project_material_material_cycle_path(material_cycle.project, material_cycle.material, material_cycle) %></td>
        <%= raw @query.inline_columns.map {|column| "<td class=\"#{column.css_classes}\">#{column_content(column, material_cycle)}</td>"}.join %>
        <td class="buttons">
        <% if material_cycle.editable_by?(User.current) -%>
          <%= link_to image_tag('edit.png'), edit_project_material_material_cycle_path(material_cycle.project, material_cycle.material, material_cycle),
                                             :title => l(:button_edit) %>
        <% end %>
        <% if material_cycle.destroyable_by?(User.current) -%>                                             
          <%= link_to image_tag('delete.png'), project_material_material_cycle_path(material_cycle.project, material_cycle.material, material_cycle),
                                               :data => {:confirm => l(:text_are_you_sure)},
                                               :method => :delete,
                                               :title => l(:button_delete) %>
        <% end -%>
        </td>
      </tr>
      <% end -%>
    </tbody>
  </table>
</div>

<% end -%>

app/views/material_cycles/edit.html.erb
<h2><%= l(:label_material_cycle_edit) %></h2>

<%= labelled_form_for :material_cycle, @material_cycle, :url => {:action => 'update', :id => @material_cycle.id}, :html => { :multipart => true, :method => :put, :id => 'material_cycle_form'} do |f|  %> 
  <%= render :partial => 'form', :locals => {:f => f}  %> 
  <%= submit_tag l(:button_save) -%>
<% end -%>


<% content_for :header_tags do %>
  <%= stylesheet_link_tag :materials, :plugin => 'redmine_materials' %>
<% end %>

app/views/material_cycles/entry.html.erb
<h2><%= l(:label_material_cycle_entry) %></h2>

<%= labelled_form_for :material_cycle, @material_cycle, :url => {:action => 'create', :stage => MaterialCycle::STAGE_ENTRY }, :html => { :multipart => true, :id => 'material_cycle_form'} do |f|  %> 
  <%= render :partial => 'form', :locals => {:f => f}  %> 
  <%= submit_tag l(:button_save) -%>
<% end -%>


app/views/material_cycles/index.html.erb
<div class="contextual">
<%= link_to_if_authorized l(:label_material_cycle_entry), {:controller => "material_cycles", :action => "entry", :project_id => @project, :material_id => @material}, :class => 'icon icon-material-cycle-entry' if @material.can_cycle_entry? %>
<%= link_to_if_authorized l(:label_material_cycle_middle), {:controller => "material_cycles", :action => "middle", :project_id => @project, :material_id => @material}, :class => 'icon icon-material-cycle-middle' if @material.can_cycle_middle? %>
<%= link_to_if_authorized l(:label_material_cycle_exit), {:controller => "material_cycles", :action => "exit", :project_id => @project, :material_id => @material}, :class => 'icon icon-material-cycle' if @material.can_cycle_exit? %>

</div>

<% html_title(@query.new_record? ? l(:label_material_cycles) : @query.name) %>
<h2><%= @query.new_record? ? link_to("#{l(:label_material)} ##{@material.id} #{@material.name}", project_material_path(@project, @material)) + " " + l(:label_material_cycles) : @query.name %></h2>

<%= form_tag({ :controller => 'material_cycles', :action => 'index', :set_filter => 1, :project_id => @project, :material_id => @material },
            :method => :get, :id => 'query_form') do %>
  <div id="query_form_with_buttons" class="hide-when-print">
    <%= hidden_field_tag 'set_filter', '1' %>
    <div id="query_form_content">
    <fieldset id="filters" class="collapsible <%= @query.new_record? ? "" : "collapsed" %>">
      <legend onclick="toggleFieldset(this);"><%= l(:label_filter_plural) %></legend>
      <div style="<%= @query.new_record? ? "" : "display: none;" %>">
        <%= render :partial => 'queries/filters', :locals => {:query => @query} %>
      </div>
    </fieldset>
    <fieldset class="collapsible collapsed">
      <legend onclick="toggleFieldset(this);"><%= l(:label_options) %></legend>
      <div style="display: none;">
        <table>
          <tr>
            <td><%= l(:field_column_names) %></td>
            <td><%= render_query_columns_selection(@query) %></td>
          </tr>
          <tr>
            <td><label for='group_by'><%= l(:field_group_by) %></label></td>
            <td><%= select_tag('group_by',
                               options_for_select(
                                 [[]] + @query.groupable_columns.collect {|c| [c.caption, c.name.to_s]},
                                 @query.group_by)
                       ) %></td>
          </tr>
          <tr>
            <td><%= l(:button_show) %></td>
            <td><%= available_block_columns_tags(@query) %></td>
          </tr>
          <tr>
            <td><%= l(:label_total_plural) %></td>
            <td><%= available_totalable_columns_tags(@query) %></td>
          </tr>
        </table>
      </div>
    </fieldset>
    </div>
    <p class="buttons">
    <%= link_to_function l(:button_apply), '$("#query_form").submit()', :class => 'icon icon-checked' %>
    <%= link_to l(:button_clear), { :set_filter => 1, :project_id => @project, :material_id => @material }, :class => 'icon icon-reload'  %>
    <% if @query.new_record? && User.current.allowed_to?(:save_queries, @project, :global => true) %>
        <%= link_to_function l(:button_save),
                             "$('#query_form').attr('action', '#{ @project ? new_project_query_path(@project) : new_query_path }').submit()",
                             :class => 'icon icon-save' %>
    <% end %>
    </p>
  </div>
<% end %>

<%= error_messages_for 'query' %>
<% if @query.valid? %>
  <% if @material_cycles.empty? %>
    <p class="nodata"><%= l(:label_no_data) %></p>
  <% else %>
    <%= render_query_totals(@query) %>
    <%= render :partial => 'list', :locals => {:material_cycles => @material_cycles, :query => @query} %>
    <span class="pagination"><%= pagination_links_full @material_cycles_pages, @material_cycles_count %></span>
  <% end %>
  <% other_formats_links do |f| %>
      <%= f.link_to 'CSV', :url => params %>
  <% end %>
<% end %>

app/views/material_cycles/show.html.erb
<div class="contextual">
  <%= link_to l(:button_edit), {:controller => "material_cycles", :action => "edit", :id => @material_cycle}, :class => 'icon icon-edit' if !@material_cycle.blank? && @material_cycle.editable_by?(User.current) %>
  <%= link_to_if_authorized l(:button_duplicate), {:controller => 'material_cycles', :action => 'new', :project_id => @project, :material_id => @material, :copy_from => @material_cycle }, :class => 'icon icon-duplicate' %>
  <%= link_to l(:button_delete), {:controller => "material_cycles", :action => "destroy", :id => @material_cycle}, :confirm => l(:text_are_you_sure), :method => :delete, :class => 'icon icon-del' if !@material_cycle.nil? && @material_cycle.destroyable_by?(User.current) %>
</div>
<h2>
  <%= link_to("#{l(:label_material_belong)}#{l(:label_material)} ##{@material.id}", project_material_path(@project, @material)) %>
</h2>

<div class="issue details">
  <div class="subject">
  <h3>
    <%= "#{l(:label_material_cycle)} ##{@material_cycle.id}" %>
  </h3>
  </div>
  <p class="author">
    <%= authoring @material_cycle.created_at, @material_cycle.author %>.
    <% if @material_cycle.created_at != @material_cycle.updated_at %>
      <%= l(:label_updated_time, time_tag(@material_cycle.updated_at)).html_safe %>.
    <% end %>
  </p>
  
  <<%= Redmine::VERSION.to_s > '3.2' ? 'div' : 'table' %> class="attributes">
    <%= issue_fields_rows do |rows|
      rows.left l(:field_stage), @material_cycle.stage_name
      rows.right l(:field_event_type), @material_cycle.type_name
      rows.left l(:field_order_no), @material_cycle.order_no
      rows.right l(:field_location), @material_cycle.location
      rows.left l(:field_outsider), @material_cycle.outsider
      rows.right l(:field_value), @material_cycle.value
      rows.left l(:field_location), @material_cycle.location
      rows.right l(:field_purpose), @material_cycle.purpose_name
      rows.left l(:field_warehouse), @material_cycle.warehouse.blank? ? "-" : @material_cycle.warehouse.name
      rows.right l(:field_issue), @material_cycle.issue.nil? ? "- " : link_to(@material_cycle.issue.subject, issue_path(@material_cycle.issue))
    end %>
  </<%= Redmine::VERSION.to_s > '3.2' ? 'div' : 'table' %>>
  