config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
resources :projects do
  resources :materials
end

resources :projects do
  resources :materials do
    resources :material_cycles do
      collection do
        get "entry"
        get "middle"
        get "exit"
      end
    end
  end
  resources :material_imports, :only => [:new, :create, :show] do
    member do
      get :settings
      post :settings
      get :mapping
      post :mapping
      get :run
      post :run
    end
  end
end

resources :material_categories

resources :warehouses

resources :materials, :only => [:index, :show]

resources :material_comments, :only => [:create, :destroy]

match 'auto_completes/materials' => 'auto_completes#materials', :via => :get, :as => 'auto_complete_materials'

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :find_project_by_project_id, :only => [:new, :create, :show, :edit, :destroy, :update]
  before_action :set_material, only: [:show, :edit, :update, :destroy]
  before_action :find_optional_project, :only => :index
  
  helper :materials
  include MaterialsHelper
  helper :issues
  helper :sort
  include SortHelper
  helper :queries
  include QueriesHelper
  helper :attachments
  include AttachmentsHelper
  helper :material_queries
  include MaterialQueriesHelper
  
  def index
    retrieve_query('material')
    sort_init(@query.sort_criteria.empty? ? [['purchase_date', 'desc']] : @query.sort_criteria)
    sort_update(@query.sortable_columns)
    
    case params[:format]
    when 'csv', 'pdf'
      @limit = Setting.issues_export_limit.to_i
    when 'xml', 'json'
      @offset, @limit = api_offset_and_limit
    else
      @limit = per_page_option
    end
    
    @materials = @query.results_scope(
      :include => :projects,
      :search => params[:search],
      :order => sort_clause,
      :limit  =>  @limit,
      :offset =>  @offset
    )
    
    
    scope = material_scope(:order => sort_clause).
      includes(:project)

    @materials_count = scope.count
    
    @materials_pages = Paginator.new(@materials_count, @limit, params['page'])


    respond_to do |format|
      format.html {
        @materials = scope.offset(@materials_pages.offset).limit(@materials_pages.per_page).to_a
        render :layout => !request.xhr?
      }
      format.api
      format.csv { send_data(materials_to_csv(@materials), :type => 'text/csv; header=present', :filename => 'materials.csv') }
    end
  end


  def new
    @material = @project.materials.new
    parent_id = params[:parent_id]
    if !parent_id.nil?
      @material.parent_material_id = parent_id
    end
    (render_403; return false) unless @material.creatable_by?(User.current, @project)
    
    # set default
    @material.status = '0'
    @material.amount = 1
    @material.property = '0'
    @material.copy_from(params[:copy_from]) if params[:copy_from]
  end


  def edit
    (render_403; return false) unless @material.editable_by?(User.current)
  end


  def show
    (render_403; return false) unless @material.visible?(User.current)
    @comments = @material.comments.to_a
    @comments.reverse! if User.current.wants_comments_in_reverse_order?
  end
  
  def destroy
    (render_403; return false) unless @material.destroyable_by?(User.current)
    
    if @material.destroy
      flash[:notice] = l(:notice_successful_delete)
    else
      flash[:error] = l(:notice_unsuccessful_save)
    end
    
    respond_to do |format|
      format.html { redirect_to :action => "index", :project_id => @material.project }
      format.api  { head :ok }
    end
  end
  
  def create
    @material = @project.materials.build(material_params)
    (render_403; return false) unless @material.creatable_by?(User.current, @project)
    @material.author = User.current
    @material.project = @project
    update_handover_at
    update_location_since
    update_use_since
    update_purchase_at
    
    respond_to do |format|
      if @material.save
        attachments = Attachment.attach_files(@material, (params[:attachments] || (params[:material] && params[:material][:uploads])))
        render_attachment_warning_if_needed(@material)

        flash[:notice] = l(:notice_material_create_success)
        format.html { redirect_to :action => "show", :id => @material}
        format.json { render :show, status: :created, location: @material }
      else
        format.html { render :new }
        format.json { render json: @material.errors, status: l(:notice_material_create_fail) }
      end
    end
  end
  
  def update
    (render_403; return false) unless @material.editable_by?(User.current)
    if @material.update_attributes(material_params)
      update_handover_at
      update_location_since
      update_use_since
      update_purchase_at
      attachments = Attachment.attach_files(@material, (params[:attachments] || (params[:material] && params[:material][:uploads])))
      render_attachment_warning_if_needed(@material)
      flash[:notice] = l(:notice_material_update_success)
      respond_to do |format|
        format.html { redirect_to :action => "show", :id => @material }
        format.api  { head :ok }
      end
    else
      respond_to do |format|
        format.html { render :action => "edit"}
        format.api  { render_validation_errors(@material) }
      end
    end
  end
  
  private
    def material_scope(options={})
      scope = @query.results_scope(options)
    end
    
    def material_params
      params.require(:material).permit( :project_id,
                                      :name,
                                      :inner_code,
                                      :brand,
                                      :device_no,
                                      :category_id,
                                      :parent_material_id,
                                      :amount,
                                      :original_value,
                                      :current_value,
                                      :use_since,
                                      :user_id,
                                      :handover_id,
                                      :author_id,
                                      :owner_id,
                                      :responsible_by_id,
                                      :purchaser_id,
                                      :purchase_at,
                                      :use_since,
                                      :handover_at,
                                      :location,
                                      :location_since,
                                      :detail,
                                      :property,
                                      :status,
                                      :remark)
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.find(params[:id])
    end
    
    def update_handover_at
      if params[:handover_at_time] && params[:handover_at_time].to_s.gsub(/\s/, "").match(/^(\d{1,2}):(\d{1,2})$/)
        handover_at = @material.handover_at.change({:hour => $1.to_i % 24, :min => $2.to_i % 60}) if @material.handover_at.present?
        if @material.new_record?
          @material.handover_at = handover_at
        else
          @material.update_attribute(:handover_at, handover_at)
        end
      end
    end
    
    def update_use_since
      if params[:use_since_time] && params[:use_since_time].to_s.gsub(/\s/, "").match(/^(\d{1,2}):(\d{1,2})$/)
        use_since = @material.use_since.change({:hour => $1.to_i % 24, :min => $2.to_i % 60}) if @material.use_since.present?
        if @material.new_record?
          @material.use_since = use_since
        else
          @material.update_attribute(:use_since, use_since)
        end
      end
    end
    
    def update_purchase_at
      if params[:purchase_at_time] && params[:purchase_at_time].to_s.gsub(/\s/, "").match(/^(\d{1,2}):(\d{1,2})$/)
        purchase_at = @material.purchase_at.change({:hour => $1.to_i % 24, :min => $2.to_i % 60}) if @material.purchase_at.present?
        if @material.new_record?
          @material.purchase_at = purchase_at
        else
          @material.update_attribute(:purchase_at, purchase_at)
        end
      end
    end
    
    
    def update_location_since
      if params[:location_since_time] && params[:location_since_time].to_s.gsub(/\s/, "").match(/^(\d{1,2}):(\d{1,2})$/)
        location_since = @material.location_since.change({:hour => $1.to_i % 24, :min => $2.to_i % 60}) if @material.location_since.present?
        if @material.new_record?
          @material.location_since = location_since
        else
          @material.update_attribute(:location_since, location_since)
        end
      end
    end
end

app/helpers/materials_helper.rb
module MaterialsHelper
  def material_categories_for_select(selected = nil)
    @material_categories ||= MaterialCategory.order(:lft).all
  end

  def material_types_for_select
    s = ''
    s.html_safe
  end

  def material_category_tree_options_for_select(material_categories, options = {})
    s = ''
    MaterialCategory.category_tree(material_categories) do |material_category, level|
      name_prefix = (level > 0 ? '&nbsp;' * 2 * level + '&#187; ' : '').html_safe
      tag_options = {:value => material_category.id}
      if material_category == options[:selected] || (options[:selected].respond_to?(:include?) && options[:selected].include?(material_category))
        tag_options[:selected] = 'selected'
      else
        tag_options[:selected] = nil
      end
      tag_options.merge!(yield(material_category)) if block_given?
      s << content_tag('option', name_prefix + h(material_category.name), tag_options)
    end
    s.html_safe
  end

  def material_category_url(category_id, options={})
    {:controller => 'materials',
     :action => 'index',
     :set_filter => 1,
     :project_id => @project,
     :fields => [:category_id],
     :values => {:category_id => [category_id]},
     :materials => {:category_id => '='}}.merge(options)
  end

  def material_category_tree_tag(material, options={})
    return "" if material.category.blank?
    material.category.self_and_ancestors.map do |category|
      link_to category.name, material_category_url(category.id, options)
    end.join(' &#187; ').html_safe
  end

  # define the status' enum list
  def collection_for_status_select
    [[l(:label_material_status_normal), Material::STATUS_NORMAL],
     [l(:label_material_status_useless), Material::STATUS_USELESS],
     [l(:label_material_status_lock), Material::STATUS_LOCK],
     [l(:label_material_status_other), Material::STATUS_OTHER]]
  end
  
  # define the property's enum list
  def collection_for_property_select
    [[l(:label_material_property_inner), Material::PROPERTY_INNER],
     [l(:label_material_property_outside), Material::PROPERTY_OUTSIDE],
     [l(:label_material_property_personal), Material::PROPERTY_PERSONAL],
     [l(:label_material_property_other), Material::PROPERTY_OTHER]]
  end
  
  def materials_to_csv(materials)
    if materials.nil?
      return
    end
    decimal_separator = l(:general_csv_decimal_separator)
    encoding = l(:general_csv_encoding)
    export = FCSV.generate(:col_sep => l(:general_csv_separator)) do |csv|
      # csv header fields
      headers = [ "#",
                  'Inner Code',
                  'Name',
                  'Category',
                  'Parent',
                  'Brand',
                  'Amount',
                  'Original Value',
                  'Current Value',
                  'User',
                  'Use Since',
                  'Purchaser',
                  'Purchase At',
                  'Handover',
                  'Handover At',
                  'Location',
                  'Locate Since',
                  'Responsible By',
                  'Owner',
                  'Device No',
                  'Status',
                  'Property',
                  'Remark',
                  'Details',
                  'Author',
                  'Created At',
                  'Updated At'
                  ]

      csv << headers.collect {|c| Redmine::CodesetUtil.from_utf8(c.to_s, encoding) }
      # csv lines
      materials.each do |material|
        fields = [material.id,
                  material.inner_code,
                  material.name,
                  material.category ? material.category.name : "",
                  material.parent_material_id ? material.parent_material.name : "",
                  material.brand,
                  material.amount,
                  material.original_value,
                  material.current_value,
                  material.user_id ? material.user.name : "",
                  material.use_since,
                  material.purchaser_id ? material.purchaser.name : "",
                  material.purchase_at,
                  material.handover_id ? material.handover.name : "",
                  material.handover_at,
                  material.location,
                  material.location_since,
                  material.responsible_by_id ? material.responsible_by.name : "",
                  material.owner_id ? material.owner.name : "",
                  material.device_no,
                  material.status,
                  material.property,
                  material.remark,
                  material.detail,
                  material.author_id ? material.author.name : "",
                  format_time(material.created_at),
                  format_time(material.updated_at)
                  ]
        csv << fields.collect {|c| Redmine::CodesetUtil.from_utf8(c.to_s, encoding) }
      end
    end
    export
  end
  
  def importer_link
    project_material_imports_path
  end

  def importer_show_link(importer, project)
    project_material_import_path(:id => importer, :project_id => project)
  end

  def importer_settings_link(importer, project)
    settings_project_material_import_path(:id => importer, :project => project)
  end

  def importer_run_link(importer, project)
    run_project_material_import_path(:id => importer, :project_id => project, :format => 'js')
  end

  def link_to_material(material)
    link_to material.name, material_path(material)
  end

end

app/views/materials/_form.html.erb
<%= error_messages_for 'material' %>

<div class="box tabular attributes">
  <div class="splitcontentleft">
    <p><%= f.text_field :inner_code, :label => :field_inner_code, :required => true %></p>
    <p><%= f.text_field :name, :label => :field_material_name, :required => true %></p>
    <p class="category"><%= f.select :category_id, material_category_tree_options_for_select(material_categories_for_select, :selected => @material.category), :label => l(:field_category), :required => false, :include_blank => true %></p>
    <p id="parent_material"><%= f.text_field :parent_material_id, :size => 25 %></p>
    <%= javascript_tag "observeAutocompleteField('material_parent_material_id', '#{escape_javascript auto_complete_materials_path(:project_id => @project)}')" %>
    <p><%= f.text_field :brand, :label => :field_brand %></p>
    <p><%= f.text_field :amount, :label => l(:field_amount), :size => 10 %></p>
    <p><%= f.text_field :original_value, :label => l(:field_original_value), :size => 10 %></p>
    <p><%= f.text_field :current_value, :label => l(:field_current_value), :size => 10 %></p>
    <p class="object-select"><%= f.select :status, collection_for_status_select, :include_blank => true, :label => l(:field_status) %></p>
    <p class="object-select"><%= f.select :property, collection_for_property_select, :include_blank => true, :label => l(:field_property) %></p>
    <p><%= f.text_field :device_no, :label => :field_device_no %></p>
  </div>

  <div class="splitcontentright">
    <p class="object-select"><%= f.select :user_id, principals_options_for_select(@project.assignable_users, @material.user), :include_blank => true, :label => l(:field_user) %></p>
    <p>
	  <%= f.date_field :use_since, :size => 12, :value => @material.use_since ? @material.use_since.to_date : nil, :label => l(:field_use_since) %><%= text_field_tag "use_since_time", @material.use_since_time, :size => 5 %><%= calendar_for('material_use_since') %>    	
    </p>
	<p class="object-select"><%= f.select :purchaser_id, principals_options_for_select(@project.assignable_users, @material.purchaser), :include_blank => true, :label => l(:field_purchaser) %></p>
    <p>
	  <%= f.date_field :purchase_at, :size => 12, :value => @material.purchase_at ? @material.purchase_at.to_date : nil, :label => l(:field_purchase_at) %><%= text_field_tag "purchase_at_time", @material.purchase_at_time, :size => 5 %><%= calendar_for('material_purchase_at') %>
    </p>
    <p><%= f.text_field :location, :label => :field_location %></p>
    <p>
   	  <%= f.date_field :location_since, :size => 12, :value => @material.location_since ? @material.location_since.to_date : nil, :label => l(:field_location_since) %><%= text_field_tag "location_since_time", @material.location_since_time, :size => 5 %><%= calendar_for('material_location_since') %>
    </p>
    <p class="object-select"><%= f.select :handover_id, principals_options_for_select(@project.assignable_users, @material.handover), :include_blank => true, :label => l(:field_handover) %></p>
    <p>
  	  <%= f.date_field :handover_at, :size => 12, :value => @material.handover_at ? @material.handover_at.to_date : nil, :label => l(:field_handover_at) %><%= text_field_tag "handover_at_time", @material.handover_at_time, :size => 5 %><%= calendar_for('material_handover_at') %>    	
    </p>
    <p class="object-select"><%= f.select :owner_id, principals_options_for_select(@project.assignable_users, @material.owner), :include_blank => true, :label => l(:field_owner) %></p>
    <p class="object-select"><%= f.select :responsible_by_id, principals_options_for_select(@project.assignable_users, @material.responsible_by), :include_blank => true, :label => l(:field_responsible_by) %></p>
    <p><%= f.text_field :remark, :label => :field_remark, :size => 30 %></p>
  </div>
  
  
  <div style="clear:both;"> 
    <p><%= f.text_area :detail, :cols => 60, :rows => 5, :class => 'wiki-edit' %><%= wikitoolbar_for 'material_detail' %></p>
  </div>
  
  <fieldset><legend><%= l(:label_attachment_plural) %></legend>
  <p><%= render :partial => 'attachments/form', :locals => {:container => @material} %></p>
  </fieldset>
  <br>
</div>

app/views/materials/_list.html.erb
<%= form_tag({}) do -%>
<%= hidden_field_tag 'back_url', url_for(params), :id => nil %>
<div class="autoscroll">
  <table class="list materials issues">
    <thead>
      <tr>
        <th class="checkbox hide-when-print">
          <%= check_box_tag 'check_all', '', false, :class => 'toggle-selection',
                :title => "#{l(:button_check_all)}/#{l(:button_uncheck_all)}" %>
        </th>
        <th>#</th>
        <% @query.inline_columns.each do |column| %>
          <%= Redmine::VERSION.to_s >= '3.4' ? column_header(@query, column) : column_header(column) %>
        <% end %>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% materials.each do |material| -%>
      <tr id="material-<%= material.id %>" class="material <%= cycle('odd', 'even') %>">
      <!--<tr class="material <%= cycle("odd", "even") %> hascontextmenu">-->
        <td class="checkbox hide-when-print"><%= check_box_tag("ids[]", material.id, false, :id => nil) %></td>
        <td class="id"><%= link_to material.id, project_material_path(material.project, material) %></td>
        <%= raw @query.inline_columns.map {|column| "<td class=\"#{column.css_classes}\">#{column_content(column, material)}</td>"}.join %>
        <td class="buttons">
        <% if material.editable_by?(User.current) -%>
          <%= link_to image_tag('edit.png'), edit_project_material_path(material.project, material),
                                             :title => l(:button_edit) %>
        <% end %>
        <% if material.destroyable_by?(User.current) -%>                                             
          <%= link_to image_tag('delete.png'), project_material_path(material.project, material),
                                               :data => {:confirm => l(:text_are_you_sure)},
                                               :method => :delete,
                                               :title => l(:button_delete) %>
        <% end -%>
        </td>
      </tr>
      <% end -%>
    </tbody>
  </table>
</div>

<% end -%>

app/views/materials/edit.html.erb
<h2><%= l(:label_material_edit) %></h2>

<%= labelled_form_for :material, @material, :url => {:action => 'update', :id => @material.id}, :html => { :multipart => true, :method => :put, :id => 'material_form'} do |f|  %> 
  <%= render :partial => 'form', :locals => {:f => f}  %> 
  <%= submit_tag l(:button_save) -%>
<% end -%>


<% content_for :header_tags do %>
  <%= stylesheet_link_tag :materials, :plugin => 'redmine_materials' %>
<% end %>

app/views/materials/index.html.erb
<div class="contextual">

<%= link_to_if_authorized l(:label_material_new), {:controller => "materials", :action => "new", :project_id => @project}, :class => 'icon icon-add' %>
<%= link_to_if_authorized l(:label_import_materials), {:controller => 'material_imports', :action => 'new', :project_id => @project}, :class => 'icon icon-import', :id => 'import_from_csv' %>

</div>

<% html_title(@query.new_record? ? l(:label_materials) : @query.name) %>
<h2><%= @query.new_record? ? l(:label_materials) : @query.name %></h2>

<%= form_tag({ :controller => 'materials', :action => 'index', :project_id => @project },
            :method => :get, :id => 'query_form') do %>
  <div id="query_form_with_buttons" class="hide-when-print">
    <%= hidden_field_tag 'set_filter', '1' %>
    <div id="query_form_content">
    <fieldset id="filters" class="collapsible <%= @query.new_record? ? "" : "collapsed" %>">
      <legend onclick="toggleFieldset(this);"><%= l(:label_filter_plural) %></legend>
      <div style="<%= @query.new_record? ? "" : "display: none;" %>">
        <%= render :partial => 'queries/filters', :locals => {:query => @query} %>
      </div>
    </fieldset>
    <fieldset class="collapsible collapsed">
      <legend onclick="toggleFieldset(this);"><%= l(:label_options) %></legend>
      <div style="display: none;">
        <table>
          <tr>
            <td><%= l(:field_column_names) %></td>
            <td><%= render_query_columns_selection(@query) %></td>
          </tr>
          <tr>
            <td><label for='group_by'><%= l(:field_group_by) %></label></td>
            <td><%= select_tag('group_by',
                               options_for_select(
                                 [[]] + @query.groupable_columns.collect {|c| [c.caption, c.name.to_s]},
                                 @query.group_by)
                       ) %></td>
          </tr>
          <tr>
            <td><%= l(:button_show) %></td>
            <td><%= available_block_columns_tags(@query) %></td>
          </tr>
          <tr>
            <td><%= l(:label_total_plural) %></td>
            <td><%= available_totalable_columns_tags(@query) %></td>
          </tr>
        </table>
      </div>
    </fieldset>
    </div>
    <p class="buttons">
    <%= link_to_function l(:button_apply), '$("#query_form").submit()', :class => 'icon icon-checked' %>
    <%= link_to l(:button_clear), { :set_filter => 1, :project_id => @project }, :class => 'icon icon-reload'  %>
    <% if @query.new_record? && User.current.allowed_to?(:save_queries, @project, :global => true) %>
        <%= link_to_function l(:button_save),
                             "$('#query_form').attr('action', '#{ @project ? new_project_query_path(@project) : new_query_path }').submit()",
                             :class => 'icon icon-save' %>
    <% end %>
    </p>
  </div>
<% end %>

<%= error_messages_for 'query' %>
<% if @query.valid? %>
  <% if @materials.empty? %>
    <p class="nodata"><%= l(:label_no_data) %></p>
  <% else %>
    <%= render_query_totals(@query) %>
    <%= render :partial => 'list', :locals => {:materials => @materials, :query => @query} %>
    <span class="pagination"><%= pagination_links_full @materials_pages, @materials_count %></span>
  <% end %>
  <% other_formats_links do |f| %>
      <%= f.link_to 'CSV', :url => params %>
  <% end %>
<% end %>

app/views/materials/new.html.erb
<h2><%= l(:label_material_new) %></h2>

<%= labelled_form_for :material, @material, :url => {:action => 'create'}, :html => { :multipart => true, :id => 'material_form'} do |f|  %> 
  <%= render :partial => 'form', :locals => {:f => f}  %> 
  <%= submit_tag l(:button_save) -%>
<% end -%>


<% content_for :header_tags do %>
  <%= stylesheet_link_tag :materials, :plugin => 'redmine_materials' %>
<% end %>

app/views/materials/show.html.erb
<div class="contextual">
  <%= link_to l(:button_edit), {:controller => "materials", :action => "edit", :id => @material}, :class => 'icon icon-edit' if !@material.blank? && @material.editable_by?(User.current) %>
  <%= link_to l(:button_add_sub), {:controller => "materials", :action => "new", :parent_id => @material}, :class => 'icon icon-add' if !@material.blank? && @material.creatable_by?(User.current, @project) %>
  <%= link_to_if_authorized l(:button_duplicate), {:controller => 'materials', :action => 'new', :project_id => @project, :copy_from => @material }, :class => 'icon icon-duplicate' %>
  <%= link_to l(:button_delete), {:controller => "materials", :action => "destroy", :id => @material}, :confirm => l(:text_are_you_sure), :method => :delete, :class => 'icon icon-del' if !@material.nil? && @material.destroyable_by?(User.current) %>
  <%= link_to_if_authorized l(:label_material_cycle_entry), {:controller => "material_cycles", :action => "entry", :project_id => @project, :material_id => @material}, :class => 'icon icon-material-cycle-entry' if @material.can_cycle_entry? %>
  <%= link_to_if_authorized l(:label_material_cycle_middle), {:controller => "material_cycles", :action => "middle", :project_id => @project, :material_id => @material}, :class => 'icon icon-material-cycle-middle' if @material.can_cycle_middle? %>
  <%= link_to_if_authorized l(:label_material_cycle_exit), {:controller => "material_cycles", :action => "exit", :project_id => @project, :material_id => @material}, :class => 'icon icon-material-cycle-exit' if @material.can_cycle_exit? %>
  <%= link_to_if_authorized l(:label_material_cycle), {:controller => "material_cycles", :action => "index", :project_id => @project, :material_id => @material}, :class => 'icon icon-material-cycle' %>
</div>
<h2>
  <%= l(:label_material) %>
</h2>

<div class="issue details">
  <div class="subject">
  <h3>
    <%= "#{l(:label_material)} ##{@material.id}" %>
  </h3>
  </div>
  <p class="author">
    <%= authoring @material.created_at, @material.author %>.
    <% if @material.created_at != @material.updated_at %>
      <%= l(:label_updated_time, time_tag(@material.updated_at)).html_safe %>.
    <% end %>
  </p>
  
  <<%= Redmine::VERSION.to_s > '3.2' ? 'div' : 'table' %> class="attributes">
    <%= issue_fields_rows do |rows|
      rows.left l(:field_inner_code), @material.inner_code
      rows.right l(:field_material_name), @material.name
      rows.left l(:field_parent_material), @material.parent_material.nil? ? "-" : link_to(@material.parent_material.name, project_material_path(@project, @material.parent_material))
      rows.right l(:field_category), @material.category.present? ? material_category_tree_tag(@material) : "-" 
      rows.left l(:field_brand), @material.brand
      rows.right l(:field_amount), @material.amount
      rows.left l(:field_original_value), @material.original_value
      rows.right l(:field_current_value), @material.current_value
      rows.left l(:field_user), "#{avatar(@material.user, :size => '14')}#{@material.user ? link_to_user(@material.user) : "-"}".html_safe
      rows.right l(:field_use_since), @material.use_since && @material.use_since != "" ? format_time(@material.use_since) : "-"
      rows.left l(:field_purchaser), "#{avatar(@material.purchaser, :size => '14')}#{@material.purchaser ? link_to_user(@material.purchaser) : "-"}".html_safe
      rows.right l(:field_purchase_at), @material.purchase_at && @material.purchase_at != "" ? format_time(@material.purchase_at) : "-"
      rows.left l(:field_location), @material.location
      rows.right l(:field_location_since), @material.location_since && @material.location_since != "" ? format_time(@material.location_since) : "-"
      rows.left l(:field_handover), "#{avatar(@material.handover, :size => '14')}#{@material.handover ? link_to_user(@material.handover) : "-"}".html_safe
      rows.right l(:field_handover_at), @material.handover_at && @material.handover_at != "" ? format_time(@material.handover_at) : "-"
      rows.left l(:field_owner), "#{avatar(@material.owner, :size => '14')}#{@material.owner ? link_to_user(@material.owner) : "-"}".html_safe
      rows.right l(:field_responsible_by), "#{avatar(@material.responsible_by, :size => '14')}#{@material.responsible_by ? link_to_user(@material.responsible_by) : "-"}".html_safe
      rows.left l(:field_status), @material.status_name
      rows.right l(:field_property), @material.property_name
      rows.left l(:field_device_no), @material.device_no
      rows.right l(:field_remark), @material.remark
    end %>
  </<%= Redmine::VERSION.to_s > '3.2' ? 'div' : 'table' %>>
  
  <% if @material.detail? || (@material.respond_to?(:attachments) && @material.attachments && @material.attachments.any?) -%>
  <hr />
  <% if @material.detail? %>
    <div class="description">
      <p><strong><%=l(:field_detail)%></strong></p>
      <div class="wiki">
      <% attachments = nil %>
      <% attachments = @material.attachments %>
      <%= textilizable @material, :detail, :attachments => attachments %>
      </div>
    </div>
  <% end %>
  <%= link_to_attachments @material, :thumbnails => true %>
<% end -%>
</div>

<div id="comments" style="margin-bottom:16px;">
<h3 class="comments"><%= l(:label_comment_plural) %></h3>
<% @comments.each do |comment| %>
    <% next if comment.new_record? %>
    <div class="contextual">
    <%= link_to_if_authorized image_tag('delete.png'), {:controller => 'material_comments', :action => 'destroy', :id => @material, :comment_id => comment},
                                                       :data => {:confirm => l(:text_are_you_sure)}, :method => :delete, :title => l(:button_delete) %>
    </div>
    <h4><%= avatar(comment.author, :size => "24") %><%= authoring comment.created_on, comment.author %></h4>
    <%= textilizable(comment.comments) %>
<% end if @comments.any? %>
</div>

<% if @material.commentable? %>
  <p><%= toggle_link l(:label_comment_add), "add_comment_form", :focus => "comment_comments" %></p>
  <%= form_tag({:controller => 'material_comments', :action => 'create', :id => @material}, :id => "add_comment_form", :style => "display:none;") do %>
    <div class="box">
        <%= text_area 'comment', 'comments', :cols => 80, :rows => 15, :class => 'wiki-edit' %>
        <%= wikitoolbar_for 'comment_comments' %>
    </div>
    <p><%= submit_tag l(:button_add) %></p>
  <% end %>
<% end %>